---
apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: slatercapstone # EKS Cluster name
  region: us-east-1 # Region Code to place EKS Cluster
  version: "1.21"

managedNodeGroups:
  - name: capstone-ng # Name of node group in EKS Cluster
    instanceType: m5.large # Instance type for node group
    desiredCapacity: 2 # The number of worker nodes in EKS Cluster
    volumeSize: 8  # EBS Volume for worker node (unit: GiB)
    ssh:
      enableSsm: true
    iam:
      withAddonPolicies:
        imageBuilder: true # Add permission for AWS ECR
availabilityZones: ['us-east-1a', 'us-east-1b', 'us-east-1c', 'us-east-1d']
