# Python CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-python/ for more details
#
version: 2.1
jobs:
  build:
    docker:
        # Use the same Docker base as the project
        - image: python:3.7.3-stretch
    working_directory: ~/repo
    steps:
        - checkout
        # Download and cache dependencies
        - restore_cache:
            keys:
                - v1-dependencies-{{ checksum "requirements.txt" }}
                # fallback to using the latest cache if no exact match is found
                - v1-dependencies-
        - run:
            name: install dependencies
            command: |
              python3 -m venv venv
              . venv/bin/activate
              make install
              # Install hadolint
              wget -O /bin/hadolint https://github.com/hadolint/hadolint/releases/download/v1.16.3/hadolint-Linux-x86_64 &&\
              chmod +x /bin/hadolint
        - save_cache:
            paths:
                - ./venv
            key: v1-dependencies-{{ checksum "requirements.txt" }}
        # run lint test for docker file
        - run:
            name: run lint
            command: |
              . venv/bin/activate
              make lint
        # run eks config file
        - run:
            name: eks configuration
            command: |

  test-cluster:
    executor: aws-eks/python3
    parameters:
      cluster-name:
        description: |
          slatercapstone
        type: string
    steps:
      - kubernetes/install
      - aws-eks/update-kubeconfig-with-authenticator:
          cluster-name: << parameters.slatercapstone >>
      - run:
          command: |
            kubectl get services
          name: Test cluster
orbs:
  aws-eks: circleci/aws-eks@0.2.3
  kubernetes: circleci/kubernetes@0.4.0

workflows:
  deployment:
    jobs:
      - build
      - aws-eks/create-cluster:
          cluster-name: slatercapstone
      - test-cluster:
          cluster-name: slatercapstone
          requires:
            - aws-eks/create-cluster
      - aws-eks/delete-cluster:
          cluster-name: slatercapstone
          requires:
            - test-cluster
