# Audrey Slater Udacity Capstone project configuration file for CircleCI
#
version: 2.1

# Defines the jobs to run in this capstone project
jobs:
  build:
    docker:
        # Docker image for the project
        - image: python:3.7.3-stretch
    working_directory: ~/repo
    steps:
        - checkout
        # Download and cache dependencies
        - restore_cache:
            keys:
                - v1-dependencies-{{ checksum "requirements.txt" }}
                # Fallback to using the latest cache if no exact match is found
                - v1-dependencies-
        - run:
            name: install dependencies
            command: |
              python3 -m venv venv
              . venv/bin/activate
              make install
              # Install hadolint
              wget -O /bin/hadolint https://github.com/hadolint/hadolint/releases/download/v1.16.3/hadolint-Linux-x86_64 &&\
              chmod +x /bin/hadolint
        - save_cache:
            paths:
                - ./venv
            key: v1-dependencies-{{ checksum "requirements.txt" }}
        # Run lint test for docker file
        - run:
            name: run lint
            command: |
              . venv/bin/activate
              make lint

# This job creates the docker image and uploads it to docker hub
  run-upload-docker:
    machine:
      image: ubuntu-2004:202111-01
    steps:
      - checkout
      - run:
          name: run docker container to create docker image
          no_output_timeout: 10m
          command: |
            ./run_docker.sh
      - run:
          name: upload docker container
          no_output_timeout: 10m
          command: |
            ./upload_docker.sh ${DOCKER_USERNAME} ${DOCKER_PASSWORD}
  
  kubernetes-deployment:
    machine:
      image: ubuntu-2004:202111-01
    steps:
      - checkout
      - linux-install-aws
      - linux-install-kubectl
      - run:
          name: create kubernetes deployment using docker image
          command: |
            kubectl apply -f manifest.yml


workflows:
  deployment:
    jobs:
      - build
      - run-upload-docker:
          requires:
            - build
      - kubernetes-deployment:
          requires:
            - run-upload-docker

      
