# Audrey Slater Udacity Capstone project configuration file for CircleCI
#
version: 2.1

# Defines the jobs to run in this capstone project
jobs:
  build:
    docker:
        # Docker image for the project
        - image: python:3.7.3-stretch
    working_directory: ~/repo
    steps:
        - checkout
        # Download and cache dependencies
        - restore_cache:
            keys:
                - v1-dependencies-{{ checksum "requirements.txt" }}
                # Fallback to using the latest cache if no exact match is found
                - v1-dependencies-
        - run:
            name: install dependencies
            command: |
              python3 -m venv venv
              . venv/bin/activate
              make install
              # Install hadolint
              wget -O /bin/hadolint https://github.com/hadolint/hadolint/releases/download/v1.16.3/hadolint-Linux-x86_64 &&\
              chmod +x /bin/hadolint
        - save_cache:
            paths:
                - ./venv
            key: v1-dependencies-{{ checksum "requirements.txt" }}
        # Run lint test for docker file
        - run:
            name: run lint
            command: |
              . venv/bin/activate
              make lint

# This job creates the docker image and uploads it to docker hub
  run-upload-docker:
    machine: true
    steps:
      - checkout
      - run:
          name: run docker container to create docker image
          no_output_timeout: 10m
          command: |
            ./run_docker.sh
      - run:
          name: upload docker container
          no_output_timeout: 10m
          command: |
            ./upload_docker.sh ${DOCKER_USERNAME} ${DOCKER_PASSWORD}

  ecr-push:
    machine: true
    steps:
      - checkout
      - run:
          name: install dependencies
          command: |
            pip install awscli
      - run:
          name: push docker image to ECS
          command: |
            # retrieve authentication token
            aws ecr get-login-password --region us-east-1 | docker login -u AWS -p $(aws ecr get-login-password --region us-east-1) 186622365412.dkr.ecr.us-east-1.amazonaws.com
            # push docker image to aslatercapstone repository in ECR
            docker push 186622365412.dkr.ecr.us-east-1.amazonaws.com/aslatercapstone:latest
  
  # kubernetes-deployment:

workflows:
  deployment:
    jobs:
      - build
      - run-upload-docker:
          requires:
            - build
      - ecr-push:
          requires:
            - run-upload-docker
      #- kubernetes-deployment:
      #    requires:
      #      - ecr-push
      
